feat: automap
mapstruct/mapstruct-spring-extensions pull request #26
Opened 2021-05-04 23:59 UTC by ZhaoRd

Realize @AutoMap annotation, simplify mapstruct code

2021-05-28 14:27 UTC, Chessray requested changes
- Please don't leave any commented code.
- Why should we restrict the package name? This would be a severe step back.
- Can you please resolve the merge conflicts?

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConversionServiceAdapterGenerator.java
> +    /*private static Iterable<MethodSpec> buildMappingMethods(
Please no commented code.

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConversionServiceAdapterGenerator.java
> +    /*private static FieldSpec buildConversionServiceFieldSpec() {
Please no commented code.

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java
> +  /*protected static final String SPRING_CONVERTER_FULL_NAME =
Please no commented code.

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java
> +        //.filter(method -> method.getSimpleName().contentEquals("convert"))
Please no commented code.

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java
> +                "org.mapstruct.extensions.spring" + "." + adapterPackageAndClass.getRight())
Sorry, this would be a step back. We don't want to restrict users.

2021-05-28 14:27 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java
> +            "org.mapstruct.extensions.spring", "ConversionServiceAdapter");
This shouldn't be a fixed package name. I understand why one would that for the `@AutoMap` feature, but we can't have that as a general setting.

2021-06-13 01:51 UTC, ZhaoRd commented
@Chessray   I did it . Please check !

2021-06-13 10:26 UTC, Chessray commented
Sorry, we've got failures in the existing tests. This PR seems to deactivate some existing functionality.

2021-06-13 10:27 UTC, Chessray requested changes
Sorry, we've got failures in the existing tests. This PR seems to deactivate some existing functionality.

2021-06-13 10:29 UTC, Chessray commented on extensions/src/main/java/org/mapstruct/extensions/spring/converter/ConverterMapperProcessor.java
> +            supertype -> typeUtils.erasure(supertype).toString().equals(BASE_AUTOMAPPER_FULL_NAME))
I suspect this is the cause of the issue. Without this filter, we won't find the mappers defined in standard MapStruct style.

2021-06-13 13:37 UTC, filiphr commented
I'd like to add something that I mentioned in the original issue [comment](https://github.com/mapstruct/mapstruct-spring-extensions/issues/24#issuecomment-829044650) earlier as well.

The auto map feature is a really interesting one. Could be useful for generating mappers from DTOs / Entities. In my opinion this should be an independent project on it own because it isn't linked to Spring itself at all. You can easily add a `componentModel` to `@AutoMap` to control the component model of the generated mappers and also another property that would allow the users to define base interfaces that generated mapper should inherit from. 

You mentioned about the usage of the `IObjectMapper`. From a MapStruct point of view we do not want our users to have a 3rd party dependency on things like that, especially not runtime dependencies. Having the option the users to define the base interface(s) that each mapper should implement (through the `@AutoMap` you can easily use your own `IObjectMapper`).

I think if we can achieve these things that we can easily integrate those mappers with the extra spring extensions that we have in this repository.

I am not sure how you look at this @Chessray?

2021-06-13 18:51 UTC, Chessray commented
@filiphr I'm totally with you. The ideal thing would be the basic annotation in Mapstruct core with a default implementation that could then be overridden in some fashion. E.g. I bet that Spring extensions users would definitely expect the implementation to follow the `Converter` pattern.

2021-06-14 23:07 UTC, ZhaoRd commented
@filiphr @Chessray   Thanks for your advice. 
This problem is because
`@AutoMap`  generator  mapper interface extends `BaseAutoMapper<S, T>` not  `Converter<S, T>`.   

`IObjectMapper`  is the uniform entrance of type conversion.  `IObjectMapper` like some `ConfigurableConversionService`

I think `Converter` pattern can't do `@InheritInverseConfiguration` and `@MappingTarget`. and this two annotation is very useful.


About `IObjectMapper` ,  It use like code 
```
public class AutoMapTest{

...
@Autowired
private IObjectMapper mapper;


@Test
public void shouldMapEntityToDto(){

        // Given
        final Car car = new Car();
...
        // When
        final CarDto mappedCar = mapper.map(car, CarDto.class);

}

@Test
public void shouldMapEntityToDtoObject(){

        // Given
        final Car car = new Car();
        final CarDto carDto = new CarDto();

...
        // When
       mapper.map(car,  carDto);

}



@Test
public void shouldMapDtoToEntity(){

        // Given
        final CarDto car = new CarDto();
...
        // When
        final Car mappedCar = mapper.map(car, Car.class);

}


}
```

About `IObjectMapper` and `Converter`,  I think there are some differences：
1. By `IObjectMapper`, it can implementation of bidirectional object map. but `Converter` only  can map `Dto -> Entity` or `Entity-> Dto`
2. Use `Converter` ，client use map object, must inject different interfaces, Use `IObjectMap`, client only inject one interface
```
@Autowired
private CarDtoToEntityMapper carDtoToEntityMapper;

@Autowired
private CarEntityToDtoMapper carEntityToDtoMapper;

```
But `CarDto` map from or to `Car`,  I think one interface can working with `InheritInverseConfiguration` 。

---------

If `@AutoMap` cann't map all, can customer mapper:
```
@Mapper(componentModel = "spring")
public interface WheelsMapper extends BaseAutoMapper<List<WheelDto>,Wheels> {

}
```


If  want to use `Converter`,  I need to think about how to make it `BaseAutoMapper` extends `Converter<S,T>`  and `Converter<T,S>` , and hwo to use `ConversionService` with `@MappingTarget`

2023-08-13 06:50 UTC, filiphr commented
@Chessray should we close this PR as well and let the user create something in MapStruct core if they need such a functionality?

2023-08-14 07:01 UTC, closed without merging